############################################################
# +------------------------------------------------------+ #
# |                   Important Notes                    | #
# +------------------------------------------------------+ #
############################################################


# If you want to use special characters in this config, such as accented letters, you must save the file as UTF-8, not ANSI.

# If you receive an error when VampireS loads, check and ensure that:
#   - There are no tabs: YAML only allows spaces.
#   - Indents are correct: YAML structure is based entirely on indentation.
#   - You have "escaped" all apostrophes in your text: If you want to write "don't", for example, write "don''t" instead (note the doubled apostrophe).
#   - Text with symbols is enclosed in single or double quotation marks.
#   - Boolean options must have at least one value: true or false.

resourcepack:
  enabled: true
  kick-player-on-download-failed: true
  # Here goes the NUMBERED ip of the server the plugin is installed in.
  server-ip: "localhost"
  # The port 41000 is normally unused, but if it's used, insert another port.
  # The default port used by the plugin is 41000;
  server-port: 41000

stonemask:
  enable-crafting: true
  use: true
  activation: true

silversword:
  # The option to enable or disable the crafting of the Silver Sword, who can only damage Vampires, inflicting them triple damage.
  enable-crafting: true

stoptime:
  # The option to enable or disable the Stop Time ability.
  enable: true
  clock:
    # The option to enable or disable the crafting of the Stop Time Clock, required for the activation of the Stop Time ability.
    enable-crafting: true

doublejump:
  # The option to enable or disable the vampire's ability to double jump.
  enable: true